### ISSUE TITLE
Configure Testing suite

### ISSUE THREAD

**Issue by nileshgulia1** [mbebenita/WebAssemblyStudio#2]
It will be good to configure unit and integration tests.
I would like to work on it.Needs babel configuration also

**Comment by mbebenita** [comment]
This would be a great idea. I think to start, getting [Travis-ci](https://travis-ci.org/) working would be a great first step.

**Comment by nileshgulia1** [comment]
That right, on my way...

**Comment by mbebenita** [comment]
I enabled builds on the [Travis-ci side](https://travis-ci.org/mbebenita/WebAssemblyStudio) but it looks like the Travis config is causing the build to fail because the `clean` and `test` npm scripts are missing.

**Comment by mbebenita** [comment]
Looks like this is all fixed now.
